# Generated by Django 4.2.3 on 2023-08-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='state',
            new_name='is_active',
        ),
    ]
