# Generated by Django 4.2.3 on 2023-08-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_state_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(verbose_name='Estado'),
        ),
    ]
